### ISSUE TITLE
Inaccessible API

### ISSUE THREAD

**Issue by noszczykmichal** [GnikDroy/gutenberg_api#4]
Hi,

I was using instance of API that you've provided in docs for my own project, unfortunately since around two days it's inaccessible. I'm trying to follow docs that you've provided for creating my own instance. Yet I'm not experienced in python and before that I had never learnt it, I'm continuously running into issues that are hard for me to overcome. The project that I've created was for education purposes as well as for my portfolio but since API is inaccessible the project is totally useless. I'm wondering If you could you recreate the instance of this API on some other hosting? It would really save a lot of my time as none of API's (in fact I've found only one -[Gutendex](https://github.com/garethbjohnson/gutendex) is as good as yours.  Additionally I've found that your app using above API is not working as well (book_treasury).

Hope you will read this message soon.

BR,
Michal

**Comment by GnikDroy** [comment]
Sorry for the inconvenience. I have fixed the issue, the API should work now. 

I do not currently pay for hosting, although I might consider it if many people have a use for it.
Since you are having problems hosting, I might create a docker image for you as well.

Thank you for contributing.

**Comment by GnikDroy** [comment]
Okay, so I've

- Fixed the running instance of the API
- Setup docker so that it is easy to deploy
- Generated a fresh Project Gutenberg database
- Updated README to be marginally more friendly

I'm closing this issue since it is fixed by 5617fda76dd167ba45da98f8a92f2bfe244c5552 and bbfe77b465949d20e902e7f7e40a056245d5696a

**Comment by noszczykmichal** [comment]
Sorry for responding with delay (yet I noticed that everything works the minute you had responded in the issue). I’m so much happy you’ve managed to tackle the issue so quickly -you’ve literally made my day. As you had written in docs if I will plan to use the API on the larger scale I will definitely set up my own instance. Yet as I had told you before my project is rather for educational purposes and after development phase (which is close to the end) it will be used once in a while. So if that is ok with you I will stay with your instance for now.
Thanks for all your help.
BR,
Michal
