### ISSUE TITLE
crash instance of API

### ISSUE THREAD

**Issue by noszczykmichal** [GnikDroy/gutenberg_api#8]
Hi there,

Sorry for interrupting again, but around a week ago, your instance of the Project Gutenberg API stopped working again. I thought maybe you would have noticed it in the meantime, so I wouldn't have to bother you. But, since a few days have passed and you haven't noticed that it, I guess you must be busy with your stuff. Anyways, could you please fix in your free time and bring it back online? Please... :) 

Thanks in advance

**Comment by GnikDroy** [comment]
Sorry about that. It has been fixed. 
I will look into more robust ways to host this without costing me too much. 
Notifying me is always appreciated, so no worries.
